github:
  # GitHub 个人访问令牌
  token: "your_github_token_here"
  # 仓库路径，格式为 "用户名/仓库名"
  repository: "username/repo-name"
  # 验证码文件在仓库中的路径
  path: "code.json"
  # 刷新间隔（秒）
  interval: 3

gitee:
  # Gitee 私人令牌
  token: "your_gitee_token_here"
  # 仓库路径，格式为 "用户名/仓库名"
  repository: "username/repo-name"
  # 验证码文件在仓库中的路径
  path: "code.json"
  # 刷新间隔（秒）
  interval: 3 